<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Employee_Collection" tests="7" time="3.778">
  <testsuite name="Get all Employee Details" id="49290d5e-fd8c-469f-b514-414ecb2ad30c" timestamp="2023-08-30T23:39:06.535Z" tests="2" failures="0" errors="0" time="0.789">
    <testcase name="Status code is 200" time="0.789" classname="EmployeeCollection"/>
    <testcase name="Get the First Employee ID" time="0.789" classname="EmployeeCollection"/>
  </testsuite>
  <testsuite name="Create Employee" id="9db23c29-5929-4d4f-9325-6709e529b8af" timestamp="2023-08-30T23:39:06.535Z" tests="2" failures="2" errors="1" time="0.503">
    <system-err><![CDATA[Iteration: 0

---
testScriptError: pm.setTimeout is not a function
---
]]></system-err>
    <testcase name="Status code is 200" time="0.503" classname="EmployeeCollection">
      <failure type="AssertionFailure" message="expected response to have status code 200 but got 429">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 88d022e2-31c3-4b25-933a-ae037ebfe06f.]]>
        <![CDATA[Collection name: Employee_Collection.]]>
        <![CDATA[Request name: Create Employee.]]>
        <![CDATA[Test description: Status code is 200.]]>
        <![CDATA[Error message: expected response to have status code 200 but got 429.]]>
        <![CDATA[Stacktrace: AssertionError: expected response to have status code 200 but got 429
   at Object.eval sandbox-script.js:1:2).]]>
      </failure>
    </testcase>
    <testcase name="Capture the reponse for comparison" time="0.503" classname="EmployeeCollection">
      <failure type="AssertionFailure" message="Unexpected token '&lt;' at 1:1&#xA;&lt;!DOCTYPE html>&#xA;^">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 88d022e2-31c3-4b25-933a-ae037ebfe06f.]]>
        <![CDATA[Collection name: Employee_Collection.]]>
        <![CDATA[Request name: Create Employee.]]>
        <![CDATA[Test description: Capture the reponse for comparison.]]>
        <![CDATA[Error message: Unexpected token '<' at 1:1
<!DOCTYPE html>
^.]]>
        <![CDATA[Stacktrace: JSONError: Unexpected token '<' at 1:1
<!DOCTYPE html>
^
   at Object.eval sandbox-script.js:2:2).]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="Verify Created Employee Record" id="f2f7c631-5c91-4fe3-8b19-b5595fe9abc7" timestamp="2023-08-30T23:39:06.535Z" tests="2" failures="2" errors="0" time="0.569">
    <testcase name="Status code is 200" time="0.569" classname="EmployeeCollection">
      <failure type="AssertionFailure" message="expected response to have status code 200 but got 404">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 88d022e2-31c3-4b25-933a-ae037ebfe06f.]]>
        <![CDATA[Collection name: Employee_Collection.]]>
        <![CDATA[Request name: Verify Created Employee Record.]]>
        <![CDATA[Test description: Status code is 200.]]>
        <![CDATA[Error message: expected response to have status code 200 but got 404.]]>
        <![CDATA[Stacktrace: AssertionError: expected response to have status code 200 but got 404
   at Object.eval sandbox-script.js:1:3).]]>
      </failure>
    </testcase>
    <testcase name="Verify record is found" time="0.569" classname="EmployeeCollection">
      <failure type="AssertionFailure" message="expected undefined to equal 'success'">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 88d022e2-31c3-4b25-933a-ae037ebfe06f.]]>
        <![CDATA[Collection name: Employee_Collection.]]>
        <![CDATA[Request name: Verify Created Employee Record.]]>
        <![CDATA[Test description: Verify record is found.]]>
        <![CDATA[Error message: expected undefined to equal 'success'.]]>
        <![CDATA[Stacktrace: AssertionError: expected undefined to equal 'success'
   at Object.eval sandbox-script.js:2:3).]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="Update the Created Record" id="05b999a2-cdca-4e57-8b66-0d80c3c59dec" timestamp="2023-08-30T23:39:06.535Z" tests="1" failures="1" errors="0" time="0.486">
    <testcase name="Status code is 200" time="0.486" classname="EmployeeCollection">
      <failure type="AssertionFailure" message="expected response to have status code 200 but got 404">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 88d022e2-31c3-4b25-933a-ae037ebfe06f.]]>
        <![CDATA[Collection name: Employee_Collection.]]>
        <![CDATA[Request name: Update the Created Record.]]>
        <![CDATA[Test description: Status code is 200.]]>
        <![CDATA[Error message: expected response to have status code 200 but got 404.]]>
        <![CDATA[Stacktrace: AssertionError: expected response to have status code 200 but got 404
   at Object.eval sandbox-script.js:1:4).]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="Verify Employee Record updated" id="f87f0674-105e-4c4c-b36a-9919e907cbc5" timestamp="2023-08-30T23:39:06.535Z" tests="2" failures="0" errors="0" time="0.403">
    <testcase name="Status code is 200" time="0.403" classname="EmployeeCollection"/>
    <testcase name="Get the First Employee ID" time="0.403" classname="EmployeeCollection"/>
  </testsuite>
  <testsuite name="Delete the created Employee" id="9d8ddb56-45cb-4ca2-ac24-fc37addaf469" timestamp="2023-08-30T23:39:06.535Z" tests="2" failures="2" errors="0" time="0.480">
    <testcase name="Status code is 200" time="0.480" classname="EmployeeCollection">
      <failure type="AssertionFailure" message="expected response to have status code 200 but got 404">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 88d022e2-31c3-4b25-933a-ae037ebfe06f.]]>
        <![CDATA[Collection name: Employee_Collection.]]>
        <![CDATA[Request name: Delete the created Employee.]]>
        <![CDATA[Test description: Status code is 200.]]>
        <![CDATA[Error message: expected response to have status code 200 but got 404.]]>
        <![CDATA[Stacktrace: AssertionError: expected response to have status code 200 but got 404
   at Object.eval sandbox-script.js:1:6).]]>
      </failure>
    </testcase>
    <testcase name="Verify record is deleted" time="0.480" classname="EmployeeCollection">
      <failure type="AssertionFailure" message="expected undefined to equal 'success'">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 88d022e2-31c3-4b25-933a-ae037ebfe06f.]]>
        <![CDATA[Collection name: Employee_Collection.]]>
        <![CDATA[Request name: Delete the created Employee.]]>
        <![CDATA[Test description: Verify record is deleted.]]>
        <![CDATA[Error message: expected undefined to equal 'success'.]]>
        <![CDATA[Stacktrace: AssertionError: expected undefined to equal 'success'
   at Object.eval sandbox-script.js:2:6).]]>
      </failure>
    </testcase>
  </testsuite>
  <testsuite name="Verify Deleted Employee Record" id="26c17f44-b7e7-4eef-84d7-0236d5c1f354" timestamp="2023-08-30T23:39:06.535Z" tests="2" failures="1" errors="0" time="0.548">
    <testcase name="Status code is 200" time="0.548" classname="EmployeeCollection">
      <failure type="AssertionFailure" message="expected response to have status code 200 but got 404">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 88d022e2-31c3-4b25-933a-ae037ebfe06f.]]>
        <![CDATA[Collection name: Employee_Collection.]]>
        <![CDATA[Request name: Verify Deleted Employee Record.]]>
        <![CDATA[Test description: Status code is 200.]]>
        <![CDATA[Error message: expected response to have status code 200 but got 404.]]>
        <![CDATA[Stacktrace: AssertionError: expected response to have status code 200 but got 404
   at Object.eval sandbox-script.js:1:7).]]>
      </failure>
    </testcase>
    <testcase name="verify records should not found" time="0.548" classname="EmployeeCollection"/>
  </testsuite>
</testsuites>